name: Cygwin 5.1

on: [push, pull_request, workflow_dispatch]

jobs:
  part1:
    uses: ./.github/workflows/common.yml
    with:
      runs_on: windows-latest
      compiler: ocaml-variants.5.1.0~alpha2+options+win
      cygwin: true
      timeout: 360
      subsuite: src/array src/atomic src/bigarray src/buffer src/bytes src/domain src/dynlink src/ephemeron src/floatarray src/hashtbl src/io

  part2:
    needs: part1
    if: ${{ always() && needs.part1.outputs.skippart2 != 'true' }}
    uses: ./.github/workflows/common.yml
    with:
      runs_on: windows-latest
      compiler: ocaml-variants.5.1.0~alpha2+options+win
      cygwin: true
      timeout: 360
      subsuite: src/lazy src/neg_tests src/queue src/semaphore src/stack src/statistics src/sys src/thread src/threadomain src/weak
