name: Linux trunk debug

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      compiler: 'ocaml-variants.5.0.0+trunk'
      compiler_branch: '5.0'
      dune_profile: 'debug-runtime'
      runparam: 'v=0,V=1'
