name: 32bit trunk

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      compiler: 'ocaml-variants.5.1.0+trunk,ocaml-option-32bit'
      compiler_git_ref: refs/heads/trunk
      timeout: 360
