name: 32bit trunk

on:
  schedule:
    # Every Monday morning, at 3:33 UTC
    - cron: '33 3 * * 1'
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      compiler: 'ocaml-variants.5.4.0+trunk,ocaml-option-32bit'
      compiler_git_ref: refs/heads/trunk
      timeout: 240
